services:
  server:
    image: xxx_your_app_xxx/app
    build:
      context: ./
      dockerfile: ./common/ci/dockerfile
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      - DBHOST=postgres
      - DBPASSWD=password
      - DBNAME=composedb
  postgres:
    image: postgres:16.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=composedb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5